version: '2'
networks:
  back:
  front:
services:
  php:
    depends_on:
      - db
    build: .
    networks:
      - back
    volumes:
      - appassets:/var/www/web/assets:rw
    environment:
      DB_CHARSET: utf8
      DB_HOST: db
      DB_NAME: web
      DB_PASSWORD: web
      DB_PORT: '3306'
      DB_TABLE_PREFIX: ''
      DB_TYPE: mysql
      DB_USER: web
  db:
    image: mishamx/mysql:5.7
    environment:
      MYSQL_DATABASE: web
      MYSQL_PASSWORD: web
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: web
    networks:
      - back
  nginx:
    depends_on:
      - php
    build:
      context: .
      dockerfile:  ./docker/nginx/Dockerfile
    environment:
      APP_HOST: php
    networks:
      - back
      - front
    volumes:
    - appassets:/var/www/web/assets

  sut:
    depends_on:
      - nginx
      - php
      - db
    build: .
    environment:
      DB_CHARSET: utf8
      DB_HOST: db
      DB_NAME: web
      DB_PASSWORD: web
      DB_PORT: '3306'
      DB_TABLE_PREFIX: ''
      DB_TYPE: mysql
      DB_USER: web
    command: ./runtest.sh
    networks:
      - back
      - front


volumes:
  appassets:
