version: '2'
networks:
  back:
  front:
services:
  php:
    image: mishamx/yii-base-docker:latest
    networks:
      - back
    volumes:
      - appassets:/var/www/web/assets:rw
    environment:
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: $MYSQL_PORT
      DB_NAME: $MYSQL_DATABASE
      DB_USER: $MYSQL_USER
      DB_PASSWORD: $MYSQL_PASSWORD
      DB_CHARSET: 'utf8'
      DB_TABLE_PREFIX: ''
  db:
    image: mishamx/mysql:5.7
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - back
  nginx:
    image: mishamx/yii-base-docker:nginx_latest
    environment:
      APP_HOST: php
    networks:
      - back
      - front
    ports:
      - '$NGINX_PORT:80'
    volumes:
    - appassets:/var/www/web/assets

volumes:
  appassets:
